jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: ${JENKINS_ADMIN_USER}
          name: ${JENKINS_ADMIN_NAME}
          description: ${JENKINS_ADMIN_DESC}
          password: ${JENKINS_ADMIN_PASS}
          properties:
            - timezone:
                timeZoneName: America/Toronto